# Generated by Django 4.1.5 on 2023-01-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='overlay',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
