# Generated by Django 4.1.5 on 2023-01-15 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0002_overlay_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='BDOClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('json_name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageBDOClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bdoclass/')),
                ('bdo_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overlay.bdoclass')),
            ],
        ),
    ]
