# Generated by Django 4.1.5 on 2023-01-15 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0003_bdoclass_imagebdoclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='bdoclass',
            name='video',
            field=models.FileField(null=True, upload_to='bdovideo/'),
        ),
    ]
