# Generated by Django 4.1.5 on 2023-01-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0004_bdoclass_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bdoclass',
            name='video',
        ),
        migrations.AddField(
            model_name='bdoclass',
            name='video_awakening',
            field=models.FileField(null=True, upload_to='classvideo/awakening/'),
        ),
        migrations.AddField(
            model_name='bdoclass',
            name='video_sucession',
            field=models.FileField(null=True, upload_to='classvideo/sucession/'),
        ),
        migrations.AddField(
            model_name='imagebdoclass',
            name='awakening',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='imagebdoclass',
            name='image',
            field=models.ImageField(upload_to='classimage/'),
        ),
    ]
