# Generated by Django 4.1.5 on 2023-01-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0005_remove_bdoclass_video_bdoclass_video_awakening_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.TextField()),
                ('video', models.FileField(null=True, upload_to='customvideo/')),
            ],
        ),
    ]
