# Generated by Django 4.1.5 on 2023-01-15 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0006_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebdoclass',
            name='bdo_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='overlay.bdoclass'),
        ),
    ]
