# Generated by Django 4.1.5 on 2023-01-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0007_alter_imagebdoclass_bdo_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.TextField()),
                ('image', models.ImageField(upload_to='background/')),
            ],
        ),
    ]
