# Generated by Django 4.1.5 on 2023-03-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0010_alter_user_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='overlay',
            name='league',
            field=models.TextField(default=''),
        ),
    ]
