# Generated by Django 4.1.5 on 2023-03-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0011_overlay_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebdoclass',
            name='image',
            field=models.FileField(upload_to='classimage/'),
        ),
    ]
