# Generated by Django 4.1.5 on 2023-03-25 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0013_uservideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservideo',
            name='bdo_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_video', to='overlay.bdoclass'),
        ),
        migrations.AlterField(
            model_name='uservideo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_video', to='overlay.user'),
        ),
    ]
