# Generated by Django 4.1.5 on 2023-07-29 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0014_uservideo_bdo_class_alter_uservideo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverlayType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OverlayReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.TextField()),
                ('overlay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overlay.overlaytype')),
            ],
        ),
        migrations.AddField(
            model_name='overlay',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='overlay.overlaytype'),
        ),
    ]
