# Generated by Django 4.1.5 on 2023-07-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0015_overlaytype_overlayreference_overlay_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='overlaytype',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
