# Generated by Django 4.1.5 on 2023-07-29 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0016_overlaytype_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='background',
            name='modality',
        ),
        migrations.AddField(
            model_name='background',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='overlay.overlaytype'),
        ),
    ]
