# Generated by Django 4.1.5 on 2024-02-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0017_remove_background_modality_background_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='customvideo/'),
        ),
    ]
