# Generated by Django 4.1.5 on 2023-09-17 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_overlay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeplaylist',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='youtube_playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='youtube_overlay.youtubeplaylist'),
        ),
    ]
