# Generated by Django 4.1.5 on 2023-09-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_overlay', '0002_youtubeplaylist_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubeplaylist',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
