# Generated by Django 4.1.5 on 2023-09-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_overlay', '0003_alter_youtubeplaylist_youtube_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
