# Generated by Django 4.1.5 on 2023-09-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_overlay', '0004_youtubevideo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeplaylist',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='status',
            field=models.IntegerField(choices=[(0, 'Finalizado'), (1, 'Tocando'), (2, 'Pausado'), (3, 'Na Fila')], default=3),
        ),
    ]
