# Generated by Django 4.1.5 on 2023-09-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_overlay', '0005_youtubeplaylist_active_youtubevideo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
