# Generated by Django 4.1.5 on 2023-09-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_overlay', '0006_youtubevideo_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='privacy',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
