# Generated by Django 4.1.5 on 2023-10-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_overlay', '0007_youtubevideo_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeplaylist',
            name='random',
            field=models.BooleanField(default=False),
        ),
    ]
